# Generated by Django 2.2.4 on 2019-09-06 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0009_auto_20190805_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal', to='restaurants.Restaurant'),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='quantity',
            field=models.CharField(max_length=20),
        ),
    ]
