# Generated by Django 2.2.4 on 2019-08-09 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190809_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumer',
            name='user',
            field=models.CharField(max_length=20),
        ),
    ]
