# Generated by Django 2.2.4 on 2019-08-18 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20190809_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumer',
            name='avatar',
            field=models.ImageField(upload_to='avatar'),
        ),
        migrations.AlterField(
            model_name='courier',
            name='avatar',
            field=models.ImageField(upload_to='avatar'),
        ),
    ]
