# Generated by Django 2.2.4 on 2019-09-08 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20190818_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='courier',
            name='location',
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
