# Generated by Django 2.2.4 on 2019-09-10 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_courier_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumer',
            name='location',
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
