# Generated by Django 2.2.4 on 2019-09-10 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_consumer_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consumer',
            old_name='location',
            new_name='latitude',
        ),
        migrations.AddField(
            model_name='consumer',
            name='longitude',
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
